use std::path::PathBuf;
use std::env;

fn main() {
    let espresso_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap()).join("espresso-logic/espresso-src/");
    println!("cargo:include={}", espresso_dir.to_str().unwrap());

    cc::Build::new()
        .include(&espresso_dir)
        .opt_level(3)
        // remove warnings that clutter the build,
        // leave original code unchanged
        .warnings(false)
        .flag_if_supported("-Wno-unused-result")
        .flag_if_supported("-Wno-format-overflow")
        .file("espresso-logic/espresso-src/black_white.c")
        .file("espresso-logic/espresso-src/canonical.c")
        .file("espresso-logic/espresso-src/cofactor.c")
        .file("espresso-logic/espresso-src/cols.c")
        .file("espresso-logic/espresso-src/compl.c")
        .file("espresso-logic/espresso-src/contain.c")
        .file("espresso-logic/espresso-src/cpu_time.c")
        .file("espresso-logic/espresso-src/cubestr.c")
        .file("espresso-logic/espresso-src/cvrin.c")
        .file("espresso-logic/espresso-src/cvrm.c")
        .file("espresso-logic/espresso-src/cvrmisc.c")
        .file("espresso-logic/espresso-src/cvrout.c")
        .file("espresso-logic/espresso-src/dominate.c")
        .file("espresso-logic/espresso-src/equiv.c")
        .file("espresso-logic/espresso-src/espresso.c")
        .file("espresso-logic/espresso-src/essen.c")
        .file("espresso-logic/espresso-src/essentiality.c")
        .file("espresso-logic/espresso-src/exact.c")
        .file("espresso-logic/espresso-src/expand.c")
        .file("espresso-logic/espresso-src/gasp.c")
        .file("espresso-logic/espresso-src/gimpel.c")
        .file("espresso-logic/espresso-src/globals.c")
        .file("espresso-logic/espresso-src/hack.c")
        .file("espresso-logic/espresso-src/indep.c")
        .file("espresso-logic/espresso-src/irred.c")
        // .file("espresso-logic/espresso-src/main.c")
        .file("espresso-logic/espresso-src/map.c")
        .file("espresso-logic/espresso-src/matrix.c")
        .file("espresso-logic/espresso-src/mincov.c")
        .file("espresso-logic/espresso-src/opo.c")
        .file("espresso-logic/espresso-src/pair.c")
        .file("espresso-logic/espresso-src/part.c")
        .file("espresso-logic/espresso-src/primes.c")
        .file("espresso-logic/espresso-src/prtime.c")
        .file("espresso-logic/espresso-src/reduce.c")
        .file("espresso-logic/espresso-src/rows.c")
        .file("espresso-logic/espresso-src/set.c")
        .file("espresso-logic/espresso-src/setc.c")
        .file("espresso-logic/espresso-src/sharp.c")
        .file("espresso-logic/espresso-src/sigma.c")
        .file("espresso-logic/espresso-src/signature.c")
        .file("espresso-logic/espresso-src/signature_exact.c")
        .file("espresso-logic/espresso-src/sminterf.c")
        .file("espresso-logic/espresso-src/solution.c")
        .file("espresso-logic/espresso-src/sparse.c")
        .file("espresso-logic/espresso-src/strdup.c")
        .file("espresso-logic/espresso-src/unate.c")
        .file("espresso-logic/espresso-src/util_signature.c")
        .file("espresso-logic/espresso-src/verify.c")
        .file("src/api.c")
        .compile("espresso");
}
