[package]
name = "espresso-rs"
version = "0.1.0"
authors = ["Martin Dahl <martin.dahl@gmail.com>"]
edition = "2018"

[build-dependencies]
cc = "1.0"

[dependencies]
serial_test = "0.4.0"
rustsat = { git = "https://github.com/nfbruns/rustsat.git" }
